[qnode0158:3786492] mca_base_component_repository_open: unable to open mca_mtl_psm: libpsm_infinipath.so.1: cannot open shared object file: No such file or directory (ignored)
[qnode0157:127283] mca_base_component_repository_open: unable to open mca_mtl_psm: libpsm_infinipath.so.1: cannot open shared object file: No such file or directory (ignored)
[qnode0159:1151984] mca_base_component_repository_open: unable to open mca_mtl_psm: libpsm_infinipath.so.1: cannot open shared object file: No such file or directory (ignored)
[qnode0156:2656931] mca_base_component_repository_open: unable to open mca_mtl_psm: libpsm_infinipath.so.1: cannot open shared object file: No such file or directory (ignored)
Traceback (most recent call last):
  File "/gpfs/home/exy4679/duckdb_test/src/distributed_join_customer_orders.py", line 263, in <module>
    main()
  File "/gpfs/home/exy4679/duckdb_test/src/distributed_join_customer_orders.py", line 248, in main
    conn = partition_and_distribute_customer_and_orders(comm, rank, size)
  File "/gpfs/home/exy4679/duckdb_test/src/distributed_join_customer_orders.py", line 157, in partition_and_distribute_customer_and_orders
    con.execute("CREATE TABLE customer AS SELECT * FROM read_parquet(?)", (local_parquet_path_c,))
duckdb.duckdb.CatalogException: Catalog Error: Table with name "customer" already exists!
Traceback (most recent call last):
  File "/gpfs/home/exy4679/duckdb_test/src/distributed_join_customer_orders.py", line 263, in <module>
    main()
  File "/gpfs/home/exy4679/duckdb_test/src/distributed_join_customer_orders.py", line 248, in main
    conn = partition_and_distribute_customer_and_orders(comm, rank, size)
  File "/gpfs/home/exy4679/duckdb_test/src/distributed_join_customer_orders.py", line 157, in partition_and_distribute_customer_and_orders
    con.execute("CREATE TABLE customer AS SELECT * FROM read_parquet(?)", (local_parquet_path_c,))
duckdb.duckdb.CatalogException: Catalog Error: Table with name "customer" already exists!
Traceback (most recent call last):
  File "/gpfs/home/exy4679/duckdb_test/src/distributed_join_customer_orders.py", line 263, in <module>
    main()
  File "/gpfs/home/exy4679/duckdb_test/src/distributed_join_customer_orders.py", line 248, in main
    conn = partition_and_distribute_customer_and_orders(comm, rank, size)
  File "/gpfs/home/exy4679/duckdb_test/src/distributed_join_customer_orders.py", line 157, in partition_and_distribute_customer_and_orders
    con.execute("CREATE TABLE customer AS SELECT * FROM read_parquet(?)", (local_parquet_path_c,))
duckdb.duckdb.CatalogException: Catalog Error: Table with name "customer" already exists!
Traceback (most recent call last):
  File "/gpfs/home/exy4679/duckdb_test/src/distributed_join_customer_orders.py", line 263, in <module>
    main()
  File "/gpfs/home/exy4679/duckdb_test/src/distributed_join_customer_orders.py", line 248, in main
    conn = partition_and_distribute_customer_and_orders(comm, rank, size)
  File "/gpfs/home/exy4679/duckdb_test/src/distributed_join_customer_orders.py", line 157, in partition_and_distribute_customer_and_orders
    con.execute("CREATE TABLE customer AS SELECT * FROM read_parquet(?)", (local_parquet_path_c,))
duckdb.duckdb.CatalogException: Catalog Error: Table with name "customer" already exists!
--------------------------------------------------------------------------
Primary job  terminated normally, but 1 process returned
a non-zero exit code. Per user-direction, the job has been aborted.
--------------------------------------------------------------------------
--------------------------------------------------------------------------
mpirun detected that one or more processes exited with non-zero status, thus causing
the job to be terminated. The first process to do so was:

  Process name: [[54286,1],1]
  Exit code:    1
--------------------------------------------------------------------------
/var/spool/slurmd/job4931386/slurm_script: line 27: data: command not found
